name: PDFs

on: [push]

jobs:
  compile:
    name: Compile the tutorial
    runs-on: ubuntu-latest
    steps:
      - name: install needed packages
        run: sudo apt update &&  DEBIAN_FRONTEND=noninteractive sudo --preserve-env=DEBIAN_FRONTEND apt install -y make texlive-latex-base  texlive-latex-recommended texlive-latex-extra texlive-plain-generic texlive-fonts-extra texlive-lang-french texlive-luatex python3-pygments librsvg2-bin
      - name: retrieve sources
        uses: actions/checkout@v4
      - name: compile
        run: make
      - name: archive PDFs
        uses: actions/upload-artifact@v4
        with:
          path: |
            english/main.pdf
            french/main.pdf
            
